name: "Meeting Note"
description: Create a new ticket for a meeting note
title: "meeting: "
labels: [
  "meeting"
]
body:
  - type: textarea
    id: description
    attributes:
      label: "Description"
      description: Please enter an explicit description of your issue
      placeholder:
    validations:
      required: true