name: "Requirement"
description: Create a new ticket for a new feature
title: "srs: "
labels: [
  "srs"
]
body:
  - type: textarea
    id: description
    attributes:
      label: "Description"
      description: Please enter an explicit description of your issue
      placeholder: Short and explicit description of your incident...
    validations:
      required: true
  - type: textarea
    id: screenshot
    attributes:
      label: "Screenshots"
      description: If applicable, add screenshots to help explain your problem.
    validations:
      required: false
  - type: input
    id: requirement-url
    attributes:
      label: "Requirement"
      description: Please enter your Requirement URL
      placeholder: ex. https://github.com/requirements/xxx
    validations:
      required: false
  - type: input
    id: ui-guideline-url
    attributes:
      label: "UI Guideline"
      description: Please enter a link of UI Guideline.
    validations:
      required: false    
  - type: textarea
    id: ui-id
    attributes:
      label: "UI IDs"
      description: Please enter a list of IDs specified in the UI Guideline.
      value: |
        * 
        * 
    validations:
      required: false
  - type: textarea
    id: testcase-id
    attributes:
      label: "TestCase IDs"
      description: Please enter a list of TestCase IDs.
      value: |
        * 
        * 
    validations:
      required: false
